# Generated by Django 3.2.3 on 2021-05-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_text_choice_choice_text_pora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text_pora',
            new_name='choice_text',
        ),
    ]
